---
title: "Visualizations Practice 2"
author: "Abhilash Roy"
date: "3/25/2021"
output: pdf_document
# animation? Coffee stains?!
latex_document:
extra_dependencies: [animate, coffee4]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Including Plots


```{r pressure, echo=TRUE}
library(tidyverse) 
library(ggthemes)
library(ggrepel)
library(gridExtra)
library(ggExtra)
library(cowplot)
library(gtools)
library(knitr)
library(rmarkdown)
library(tinytex)
#datasets
library(dslabs)
library(nycflights13)
library(NHANES)
library(titanic)

murder_rate <- murders %>% summarize(rate = sum(total)/sum(population) * 10^6) %>% pull(rate)

murders %>% 
  ggplot(aes(population/10^6, total, label = abb)) +
  geom_point(aes(color = region), size = 3) + geom_text_repel(nudge_x = 0.075) + 
  theme_economist() + scale_x_log10() + scale_y_log10() + 
  xlab("Population per million (Logic Scale)") +
  ylab("Total no. of murders(Logic Scale)") + 
  geom_abline(intercept = log10(murder_rate), lty = 2, color = "darkgrey") +
  ggtitle("Murders in US in 2020") + scale_color_discrete(name = "Region")

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
